site_name: ReadTheDocs Dropdown
site_description: 'Updated version of MkDocs ReadTheDocs theme'
site_author: 'Chad Sheets'

theme_dir: rtd_dropdown

repo_url: https://github.com/cjsheets/readthedocs-dropdown

google_analytics: ['UA-10006093-5', 'readthedocs.sheets.ch']