site_name: MkDocs Basic theme
theme_dir: readthedocs-nested

repo_url: https://github.com/d0ugal/mkdocs-basic-theme

pages: 
- Home: index.md
- One:
  - One p One:
    - One p One - Two: 1/1.1/1.1-2.md
    - One p One - Three: 1/1.1/1.1-3.md
  - One p Two:
    - One p Two p One: 1/1.2/1.2.1/1.2.1-1.md